# docker-compose.dev.yml
version: '3.8'

services:
  backend:
    build:
      target: development
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      - DEBUG=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Stwórz osobny Dockerfile dla dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]