"""Add order_parts table

Revision ID: 2866c4c1cbf9
Revises: abb964d0d03a
Create Date: 2025-06-15 20:39:01.219503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2866c4c1cbf9'
down_revision = 'abb964d0d03a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_parts_id'), 'order_parts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_parts_id'), table_name='order_parts')
    op.drop_table('order_parts')
    # ### end Alembic commands ###
